# Generated by Django 2.2.7 on 2019-12-01 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_auto_20191201_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel',
            name='unique_squirrel_id',
            field=models.CharField(help_text='Unique Squirrel ID', max_length=15),
        ),
    ]
