# Generated by Django 2.2.7 on 2019-12-01 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_auto_20191201_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel',
            name='age',
            field=models.CharField(choices=[('juvenile', 'Juveline'), ('adult', 'Adult')], help_text='Age', max_length=8),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='location',
            field=models.CharField(choices=[('ground plane', 'Ground Plane'), ('above ground', 'Above Ground')], help_text='Location', max_length=12),
        ),
    ]
